### ISSUE TITLE
Cant Bundle with vite

### ISSUE THREAD

**Issue by envatic** [intlify/vue-i18n-next#1010]
### Reporting a bug?

When add to vite project and bundle I get error
```

[commonjs] A string literal cannot be used as an exported binding without `from`. (2232:52) in /Users/steve/sites/vue3-web3modal/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js
file: /Users/steve/sites/vue3-web3modal/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js:2232:52
2230: if ((process.env.NODE_ENV !== 'production')) ;
2231: 
2232: export { DatetimeFormat, NumberFormat, Translation, VERSION, createI18n, useI18n, vTDirective };
                                                          ^
error during build:
SyntaxError: A string literal cannot be used as an exported binding without `from`. (2232:52) in /Users/steve/sites/vue3-web3modal/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js
    at Parser.pp$4.raise (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:19740:13)
    at Parser.pp$8.parseExport (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:17978:16)
    at Parser.pp$8.parseStatement (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:17210:74)
    at Parser.pp$8.parseTopLevel (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:17091:21)
    at Parser.parse (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:16863:15)
    at Function.parse (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:16913:35)
    at Graph.contextParse (/Users/steve/sites/vue3-web3modal/node_modules/rollup/dist/shared/rollup.js:23017:38)
    at tryParse (/Users/steve/sites/vue3-web3modal/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:13322:12)
    at analyzeTopLevelStatements (/Users/steve/sites/vue3-web3modal/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:13341:15)
    at Object.transformAndCheckExports (/Users/steve/sites/vue3-web3modal/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:15042:68)
```

### Expected behavior

SHould build as normal

### Reproduction

Create a vite project add vue-i18n and build

### System Info

```shell
macos m1 lion
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by envatic** [comment]
Issue was in my config
I had this 
```js
define: {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        VERSION: JSON.stringify(require('./package.json').version),
    },
```

when I removed this all worked fine. I cant tell why?

**Comment by kazupon** [comment]
Thank you for your reporting!
However, We need a minimum reproduction code to reach out to the cause.
Could you give us it, please?
