### ISSUE TITLE
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

### ISSUE THREAD

**Issue by wallereducbank-zz** [intlify/vue-i18n-next#1031]
### Reporting a bug?

Warning in console.

### Expected behavior

no warnings

### Reproduction

i used command 'vue add i18n'

### System Info

```shell
"dependencies": {
        "core-js": "^3.8.3",
        "register-service-worker": "^1.7.2",
        "vue": "^3.2.13",
        "vue-i18n": "^9.1.10",
        "vue-router": "^4.0.3",
        "vuex": "^4.0.0"
      },
```

### Screenshot

![image](https://user-images.githubusercontent.com/98391614/173391076-dc69aee6-f814-4cb8-90f7-f274617078c7.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wallereducbank** [comment]
"vue": "3.2.37"
"vue-i18n": "9.1.10"
devDependencies : "@intlify/vue-i18n-loader": "4.2.0"

I fix it in vue.config.js:

`configureWebpack: config => {
    config.plugins.push(
      new webpack.DefinePlugin({
        __INTLIFY_PROD_DEVTOOLS__: false,
        __VUE_I18N_FULL_INSTALL__: true,
        __VUE_I18N_LEGACY_API__: true
      })
    )`

**Comment by yurizhang** [comment]
change imort i18n: 
import { createI18n } from "vue-i18n/index"

**Comment by Shinigami92** [comment]
@yurizhang getting these errors by just trying that 🧐

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7195563/183023098-47966792-36b5-485c-b39a-b3ff802952fd.png">

```node
Could not find a declaration file for module 'vue-i18n/index'. '/Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vue-i18n@9.2.0_vue@3.2.37/node_modules/vue-i18n/index.js' implicitly has an 'any' type.
  If the 'vue-i18n' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'vue-i18n/index';`ts(7016)
```

```node
09:14:45 [vite] page reload src/plugins/i18n.ts
Missing "./index" export in "vue-i18n" package
09:14:45 [vite] Internal server error: Missing "./index" export in "vue-i18n" package
  Plugin: vite:import-analysis
  File: /Users/shinigami/Dermalog/frontend/src/plugins/i18n.ts
      at bail (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:33604:8)
      at resolve (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:33681:10)
      at resolveExports (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34422:12)
      at resolveDeepImport (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34440:31)
      at tryNodeResolve (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34161:20)
      at Context.resolveId (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:33963:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:35216:32)
      at async TransformContext.resolve (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34981:23)
      at async normalizeUrl (file:///Users/shinigami/Dermalog/frontend/node_modules/.pnpm/vite@3.0.4_sass@1.32.13/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:40175:34)
```

**Comment by kazupon** [comment]
This warning is going to be removed in vue-i18n v9.3 or later and later.
So close it.
