### ISSUE TITLE
SyntaxError: Named export 'createI18n' not found 

### ISSUE THREAD

**Issue by productdevbook** [intlify/vue-i18n-next#1131]
### Reporting a bug?

```shell
import { createI18n, useI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
         ^^^^^^^^^^
SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
const { createI18n, useI18n } = pkg;
```

### Expected behavior

1. pnpm install
2. pnpm build
3. cd apps/docs
4. pnpm build

### Reproduction

branch: feat/date

https://github.com/huntersofbook/huntersofbook/tree/feat/date

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 17.10 GB / 31.12 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
  npmPackages:
    vitepress: 1.0.0-alpha.10 => 1.0.0-alpha.10
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reproduction!

Hmm 🤔  , I could not your reproduction same situation.
vitepress is using `vite@v3`, so `vite@v3` require native ES modules

vue-i18n v9 is not yet a full native ES modules. So we need to support it.

**Comment by productdevbook** [comment]
Sorry At first the packages were supposed to get the builder,



1. pnpm install
2. pnpm build
3. cd apps/docs
4. pnpm build

now tested,

**Comment by kazupon** [comment]
Okay, I’ve confirmed in another issue.
https://github.com/intlify/bundle-tools/issues/166

**Comment by kazupon** [comment]
I've just released `vue-i18n@9.3.0-beta.1` and `@intlify/vite-plugin-vue-i18n@7.0.0-beta.0`
Please try to install and build with those!

Thanks!

**Comment by productdevbook** [comment]
https://github.com/huntersofbook/huntersofbook/tree/fix/i18n

branch: fix/i18n


```
vitepress v1.0.0-alpha.10
✓ building client + server bundles...
⠋ rendering pages...SyntaxError: 18
    at createCompileError (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:57:19)
    at createI18nError (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.1_vue@3.2.37/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.mjs:100:12)
    at useI18n (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.1_vue@3.2.37/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.mjs:2219:15)
    at setup (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:6792:42)
    at _sfc_main.setup (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:6811:23)
    at callWithErrorHandling (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderVNode (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:292:22) {
  code: 18,
  domain: undefined
}
[Vue warn]: Component <Anonymous> is missing template or render function.
file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.1_vue@3.2.37/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.mjs:2147
                if (((process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__) &&
                                                                ^

ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined
    at Object.install (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.1_vue@3.2.37/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.mjs:2147:65)
    at Object.use (/home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3393:28)
    at Module.install (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:73:7)
    at file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:6830:113
    at Array.map (<anonymous>)
    at Object.enhanceApp (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:6830:91)
    at createApp (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:7026:15)
    at render (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:7070:29)
    at renderPage (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vitepress@1.0.0-alpha.10/node_modules/vitepress/dist/node/serve-a32ee2b7.js:40619:25)
    at build (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vitepress@1.0.0-alpha.10/node_modules/vitepress/dist/node/serve-a32ee2b7.js:40961:15)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/187125852-c4c45883-619e-4089-be3c-de2447ba5bcf.png)

some problem nuxt 3

**Comment by lakuapik** [comment]
@productdevbook same here with nuxt3

![image](https://user-images.githubusercontent.com/20186786/187174887-82de872c-25a8-49ef-9f28-481fb02d69e9.png)

**Comment by productdevbook** [comment]
@kazupon 
```
    "vue-i18n": "9.3.0-beta.2"
    "@intlify/vite-plugin-vue-i18n": "7.0.0-beta.1",
 ```
 iam update now but error 
 
![image](https://user-images.githubusercontent.com/38668796/187597495-eb7d307e-3cfc-4887-a0d8-e0be2bc4f6cc.png)

https://github.com/huntersofbook/huntersofbook/tree/fix/language
branch: fix/language

**Comment by kazupon** [comment]
@productdevbook 
Thank you for your feedback!
I've just fixed it and send PR, please wait 🙏 
https://github.com/intlify/vue-i18n-next/pull/1152

**Comment by kazupon** [comment]
> @productdevbook same here with nuxt3
> 
> ![image](https://user-images.githubusercontent.com/20186786/187174887-82de872c-25a8-49ef-9f28-481fb02d69e9.png)

BTW,  you need use default export, later `@intlify/vite-plugin-vue-i18n` v7 or later

```
import vueI18n from '@intlify/vite-plugin-vue-i18n'
```

**Comment by kazupon** [comment]
I've just released out vue-i18n 9.3.0-beta.3
Please check it!

**Comment by productdevbook** [comment]
@kazupon 

![image](https://user-images.githubusercontent.com/38668796/187603647-a0c1595f-c715-4ec0-aa03-ba5e571dd6c0.png)

https://github.com/huntersofbook/huntersofbook/tree/fix/language
branch: fix/language

**Comment by lakuapik** [comment]
> I've just released out vue-i18n 9.3.0-beta.3 Please check it!


@kazupon it works! thank you very much!

**Comment by kazupon** [comment]
@productdevbook 
Hello!
I've just released `@intlify/vite-plugin-vue-i18n` v7.0.0-beta.2
Please check it!

I've checked your awesome hundersofbook!
So, I've faced the error in it the below:

```
vitepress v1.0.0-alpha.10
✓ building client + server bundles...
⠋ rendering pages...TypeError: format2 is not a function
    at localizedFormat (file:///path/to/tmp/huntersofbook/apps/docs/docs/.vitepress/.temp/app.js:99:10)
    at watch.immediate (file:///path/to/tmp/huntersofbook/apps/docs/docs/.vitepress/.temp/app.js:2350:430)
    at callWithErrorHandling (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at callWithAsyncErrorHandling (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:128:21)
    at doWatch (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:1280:13)
    at watch (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:1209:12)
    at setup (file:///path/to/tmp/huntersofbook/apps/docs/docs/.vitepress/.temp/app.js:2341:5)
    at callWithErrorHandling (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/path/to/tmp/huntersofbook/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
✓ rendering pages...
build complete in 11.57s.
```

I seem that date-fns is not to fully support cjs/mjs
vite3 SSR (vitepress) requires esm, so you might want to check if your module is supported as a dual module.

**Comment by productdevbook** [comment]
@kazupon 
Thank you fixed,

https://huntersofbook.pages.dev/docs/ui/hdatetime/

and change language after live dont change, 

but local test, change and page refresh and fixed. Why ?

code -> https://github.com/huntersofbook/huntersofbook/blob/main/apps/docs/components/Language.vue

and brach main push

![image](https://user-images.githubusercontent.com/38668796/188065609-67368440-1521-4e2c-aaed-9d103b229d9c.png)

**Comment by kazupon** [comment]
I've checked `useTimeFromNow` 

You need to pass **`ref`** type, not the primitive value (locale.value)

https://github.com/huntersofbook/huntersofbook/blob/20f15a847859553ce8478a609bb7159cd29d06b8/packages/core/src/utils/date-fns/use-time-from-now.ts#L5

The `locale` exported from `useI18n` is already `ref`.
Your composable function should take that value and implement it to work reactively.

**Comment by productdevbook** [comment]
Thank you fixed
