### ISSUE TITLE
Error is undefined for linked translation

### ISSUE THREAD

**Issue by dargmuesli** [intlify/vue-i18n-next#1142]
### Reporting a bug?

When having a `.json` containing an unescaped `@` like e.g.

```json5
{
  "globalPlaceholderEmailAddress": "e-mail@adres.se",
  // "globalPlaceholderEmailAddress": "e-mail{'@'}adres.se" // would be correct
}
```

I receive the following error while building with nuxt:

```
 ERROR  Cannot read properties of undefined (reading 'message')                                                                                13:59:25

  at newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.2/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
  at newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.2/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at newOptions.onError (node_modules/.pnpm/@intlify+bundle-utils@3.1.0_vue-i18n@9.2.2/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at emitError (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:196:13)
  at readTokenInLinked (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:764:21)
  at readToken (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:778:20)
  at Object.nextToken (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:822:16)
  at parseLinked (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:957:31)
  at parseMessage (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1056:36)
  at parseResource (node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.1/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1095:25)
```

### Expected behavior

I'd expect the error to be set and to point me towards an unescaped `@` usage.

### Reproduction

https://codesandbox.io/s/i18n-html-to-text-urt22w?file=/pages/index.vue (taken from https://github.com/intlify/bundle-tools/issues/168)

### System Info

```shell
Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
  npmPackages:
    @intlify/eslint-plugin-vue-i18n: 2.0.0 => 2.0.0 
    vue: 3.2.37 => 3.2.37 
    vue-chartjs: 4.1.1 => 4.1.1 
    vue-croppa: 1.3.8 => 1.3.8 
    vue-datetime: 1.0.0-beta.14 => 1.0.0-beta.14 
    vue-i18n: 9.2.2 => 9.2.2 
    vue-qrcode-reader: 3.1.0 => 3.1.0 
    vue-template-compiler: 2.7.10 => 2.7.10 
    vue-tsc: 0.40.1 => 0.40.1
```

### Additional context

Here the error is undefined: https://github.com/intlify/bundle-tools/blob/553b088e16e73305cd9293aa283011775172a1bd/packages/bundle-utils/src/codegen.ts#L226
That's because the `SyntaxError` has no `message` property set, despite being constructed with a `String(msg)` here: https://github.com/intlify/vue-i18n-next/blob/e4b1d37b02ed19a1dde7acc2ab7120c1a3e736e4/packages/message-compiler/src/errors.ts#L80

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
This issue was resolved in the below release:

https://github.com/intlify/bundle-tools/releases/tag/bundle-utils%403.1.2
https://github.com/intlify/bundle-tools/releases/tag/bundle-utils%403.1.1
https://github.com/intlify/bundle-tools/releases/tag/unplugin-vue-i18n%400.6.0

we can see the syntax errors by the message compiler user-friendly

Thanks!

**Comment by dargmuesli** [comment]
Thank you! :heart:
