### ISSUE TITLE
vitepress:  Component <Anonymous> is missing template or render function.

### ISSUE THREAD

**Issue by productdevbook** [intlify/vue-i18n-next#1167]
### Reporting a bug?

```
[Vue warn]: Component <Anonymous> is missing template or render function.
SyntaxError: 17
    at createCompileError (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/@intlify+message-compiler@9.3.0-beta.3/node_modules/@intlify/message-compiler/dist/message-compiler.mjs:54:19)
    at createI18nError (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.3_vue@3.2.39/node_modules/vue-i18n/dist/vue-i18n.runtime.mjs:92:12)
    at useI18n (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/node_modules/.pnpm/vue-i18n@9.3.0-beta.3_vue@3.2.39/node_modules/vue-i18n/dist/vue-i18n.runtime.mjs:2206:15)
    at setup (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:7112:42)
    at _sfc_main.setup (file:///home/productdevbook/Documents/GitHub/huntersofbook/open-source/apps/docs/docs/.vitepress/.temp/app.js:7139:23)
```

### Expected behavior

1. pnpm install
2. pnpm build
3. cd apps/docs
4. pnpm build

### Reproduction

https://github.com/huntersofbook/huntersofbook/tree/feat/password

brach: feat/password

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 12.91 GB / 31.12 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
  npmPackages:
    @intlify/vite-plugin-vue-i18n: 7.0.0-beta.2 => 7.0.0-beta.2 
    vitepress: 1.0.0-alpha.13 => 1.0.0-alpha.13 
    vue: 3.2.39 => 3.2.39 
    vue-i18n: 9.3.0-beta.3 => 9.3.0-beta.3
```

### Screenshot

![image](https://user-images.githubusercontent.com/38668796/189532111-8a61b8aa-3852-4e11-9b55-f5efc7d7f95d.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting as always!

I've checked this issue on your repo.
I could see the same error.

Error code `17` is defined at here
https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n-core/src/errors.ts#L20

And, the error message is here:
https://github.com/intlify/vue-i18n-next/blob/master/packages/vue-i18n-core/src/errors.ts#L59-L60
`Must be called at the top of a `setup` function`

Error stacktrace, and I’ve found out for your Vue Component and found this error in `Language.vue`.
I seem that `useI18n` is called at the top of the script setup
I’m confued as to why such an error would occur. 🤔

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/190334035-1ab8f7f2-9c2d-43ce-82e0-9903e70c024a.png)

why are there 2 different vue versions. I think the error is due to this but I don't know how to fix it

**Comment by kazupon** [comment]
Thank you for your reporting!
I could reproduce that issue.
This error occurs in `@intlify/vite-plugin-vue-i18n` v7.0.0-beta 
So, I'll fix this issue.

**Comment by kazupon** [comment]
`@intlify/vite-plugin-vue-i18n` has been already deprecated. so close
thanks
