### ISSUE TITLE
Error after upgrading to Nuxt 3.0.0-rc.10

### ISSUE THREAD

**Issue by peio72** [intlify/vue-i18n-next#1174]
### Reporting a bug?

Can't launch nuxt anymore: 

ERROR  Cannot start nuxt:  The requested module '@intlify/vite-plugin-vue-i18n' does not provide an export named 'vueI18n'                                                09:43:56

  import { vueI18n } from '@intlify/vite-plugin-vue-i18n';
  ^^^^^^^
  SyntaxError: The requested module '@intlify/vite-plugin-vue-i18n' does not provide an export named 'vueI18n'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:469:26)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:448:41)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1599:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

### Expected behavior

run

### Reproduction

test

### System Info

```shell
Nuxt 3.0.0-rc.10
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
This issue is not vue-i18n-next, so I'll transfer to `intlify/bundle-tools
