### ISSUE TITLE
SyntaxError: Not available in legacy mode

### ISSUE THREAD

**Issue by skav3n** [intlify/vue-i18n-next#1193]
### Reporting a bug?

When I remove yarn.lock or increase/decrease vue-i18n version, I will get the error 'SyntaxError: Not available in legacy mode'
```
Uncaught (in promise) SyntaxError: Not available in legacy mode
    at createCompileError (message-compiler.mjs:67:19)
    at createI18nError (vue-i18n.mjs:110:89)
    at useI18n (vue-i18n.mjs:2236:23)
    at setup (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-cli-plugin-quasar/lib/loader.vue.auto-import-quasar.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/regions/search/components/table.component.vue?vue&type=script&lang=js:48:76)
    at callWithErrorHandling (runtime-core.esm-bundler.js:315:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7244:29)
    at setupComponent (runtime-core.esm-bundler.js:7199:11)
    at mountComponent (runtime-core.esm-bundler.js:5088:13)
    at processComponent (runtime-core.esm-bundler.js:5063:17)
    at patch (runtime-core.esm-bundler.js:4664:21)
```

### Expected behavior

No errors

### Reproduction

The error occurs only when dependencies in yarn.lock are 9.2.2 or above

```
"@intlify/core-base@9.2.2":
  version "9.2.2"
  resolved "https://registry.yarnpkg.com/@intlify/core-base/-/core-base-9.2.2.tgz#5353369b05cc9fe35cab95fe20afeb8a4481f939"
  integrity sha512-JjUpQtNfn+joMbrXvpR4hTF8iJQ2sEFzzK3KIESOx+f+uwIjgw20igOyaIdhfsVVBCds8ZM64MoeNSx+PHQMkA==
  dependencies:
    "@intlify/devtools-if" "9.2.2"
    "@intlify/message-compiler" "9.2.2"
    "@intlify/shared" "9.2.2"
    "@intlify/vue-devtools" "9.2.2"

"@intlify/devtools-if@9.2.2":
  version "9.2.2"
  resolved "https://registry.yarnpkg.com/@intlify/devtools-if/-/devtools-if-9.2.2.tgz#b13d9ac4b4e2fe6d2e7daa556517a8061fe8bd39"
  integrity sha512-4ttr/FNO29w+kBbU7HZ/U0Lzuh2cRDhP8UlWOtV9ERcjHzuyXVZmjyleESK6eVP60tGC9QtQW9yZE+JeRhDHkg==
  dependencies:
    "@intlify/shared" "9.2.2"

"@intlify/message-compiler@9.2.2":
  version "9.2.2"
  resolved "https://registry.yarnpkg.com/@intlify/message-compiler/-/message-compiler-9.2.2.tgz#e42ab6939b8ae5b3d21faf6a44045667a18bba1c"
  integrity sha512-IUrQW7byAKN2fMBe8z6sK6riG1pue95e5jfokn8hA5Q3Bqy4MBJ5lJAofUsawQJYHeoPJ7svMDyBaVJ4d0GTtA==
  dependencies:
    "@intlify/shared" "9.2.2"
    source-map "0.6.1"

"@intlify/shared@9.2.2":
  version "9.2.2"
  resolved "https://registry.yarnpkg.com/@intlify/shared/-/shared-9.2.2.tgz#5011be9ca2b4ab86f8660739286e2707f9abb4a5"
  integrity sha512-wRwTpsslgZS5HNyM7uDQYZtxnbI12aGiBZURX3BTR9RFIKKRWpllTsgzHWvj3HKm3Y2Sh5LPC1r0PDCKEhVn9Q==

"@intlify/vue-devtools@9.2.2":
  version "9.2.2"
  resolved "https://registry.yarnpkg.com/@intlify/vue-devtools/-/vue-devtools-9.2.2.tgz#b95701556daf7ebb3a2d45aa3ae9e6415aed8317"
  integrity sha512-+dUyqyCHWHb/UcvY1MlIpO87munedm3Gn6E9WWYdWrMuYLcoIoOEVDWSS8xSwtlPU+kA+MEQTP6Q1iI/ocusJg==
  dependencies:
    "@intlify/core-base" "9.2.2"
    "@intlify/shared" "9.2.2"
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 2.83 GB / 15.74 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.22000.120
```
```


### Screenshot

_No response_

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddeboer** [comment]
This solves the problem for me:

```javascript
const i18n = createI18n({
  legacy: false,
  ...
```

**Comment by mreduar** [comment]
> This solves the problem for me:
> 
> ```js
> const i18n = createI18n({
>   legacy: false,
>   ...
> ```

Thank you! This solved the problem

**Comment by ejimenez123** [comment]
@mreduar you are a tiger

**Comment by mreduar** [comment]
> @mreduar you are a tiger !!

🤣💪😎

**Comment by Cabezagithub** [comment]
Excellent.  Solved the problem for me too.
Really thank you.

**Comment by KitsuC** [comment]
> Close in-activity
> We need a solution to this issue, but we need the minimue reproduction code that can actually confirm the issue with anyone. we need a github repo or stackbliz where anyone can reproduce the issue.
> If you would be faced this issue agina, please you would open the new issue.
> thanks!

nice

**Comment by theotherdon** [comment]
I'm running into this error when using the Composition API. I tried this

```javascript
useI18n({ legacy: false });
```

but no dice. Has anyone else run into this?
