### ISSUE TITLE
Failed to Resolve Entry for Package "@intlify/shared"

### ISSUE THREAD

**Issue by kirklin** [intlify/vue-i18n-next#1521]
### Reporting a bug?

# Bug Description:

I encountered an issue while working with the package  in a Vite project. The error message suggests a problem with resolving the entry for the package "@intlify/shared," and it mentions a potential issue with the package's  file.vue-i18n@9.3.0package.json

## plaintext
```
 Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]

    ../../node_modules/.pnpm/vue-i18n@9.3.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1282:20:
      1282 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
    at handlePlugins (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:1282:21)
    at buildOrContextImpl (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:971:5)
    at Object.buildOrContext (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:779:5)
    at D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:2175:68
    at new Promise (<anonymous>)
    at Object.context (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:2175:27)
    at Object.context (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:2015:58)
    at prepareEsbuildOptimizerRun (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)

D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:1639
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../node_modules/.pnpm/vue-i18n@9.3.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for packag
e "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
    at failureErrorWithLog (D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:1639:15)
    at D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:1051:25
    at D:\development\celeris-web\node_modules\.pnpm\esbuild@0.18.11\node_modules\esbuild\lib\main.js:1515:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
          at packageEntryFailure (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
          at resolvePackageEntry (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
          at tryNodeResolve (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
          at Context.resolveId (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
          at Object.resolveId (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21     
          at async D:\development\celeris-web\node_modules\.pnpm\vite-plugin-inspect@0.7.38_rollup@2.79.1_vite@4.4.9\node_modules\vite-plugin-inspect\dist\index.cjs:1237:26
          at async D:\development\celeris-web\node_modules\.pnpm\vite-plugin-inspect@0.7.38_rollup@2.79.1_vite@4.4.9\node_modules\vite-plugin-inspect\dist\index.cjs:1237:26
          at async file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34,    
      id: '',
      location: {
        column: 21,
        file: '../../node_modules/.pnpm/vue-i18n@9.3.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs',
        length: 17,
        line: 8,
        lineText: "var shared = require('@intlify/shared');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: '../../node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1282,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)\n' +
              '    at handlePlugins (D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:1282:21)\n' +
              '    at buildOrContextImpl (D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:971:5)\n' +
              '    at Object.buildOrContext (D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:779:5)\n' +       
              '    at D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:2175:68\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.context (D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:2175:27)\n' +
              '    at Object.context (D:\\development\\celeris-web\\node_modules\\.pnpm\\esbuild@0.18.11\\node_modules\\esbuild\\lib\\main.js:2015:58)\n' +
              '    at prepareEsbuildOptimizerRun (file:///D:/development/celeris-web/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'
    }
  ],
  warnings: []
}

Node.js v18.15.0

```

### Expected behavior

I expected the package  to resolve dependencies correctly without encountering this error.`vue-i18n`

### Reproduction

update dependency `vue-i18n@9.3.0`
https://github.com/kirklin/celeris-web/tree/update_deps
### System Info

```shell
System:
    OS: Windows 10 10.0.23536
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 1.38 GB / 31.75 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - D:\development\celeris-web\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Spartan (44.23536.1000.0), Chromium (117.0.2045.12), ChromiumDev (118.0.2060.1)
    Internet Explorer: 11.0.23536.1000
  npmPackages:
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.3 => 0.34.3
```

### Screenshot

![image](https://github.com/intlify/vue-i18n-next/assets/17453452/0198e70a-bb03-4bd8-bbbd-1486fad34066)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by donalmurtagh** [comment]
My app is also built with Vite and I ran into the same issue after upgrading from v9.22 to v9.3.0

```
✘ [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
    at tryNodeResolve (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
    at async file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
    at async requestCallbacks.on-resolve (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
    at handlePlugins (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:786:5)
    at /Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/donal/workspace/source-space/bid-event-frontend/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///Users/donal/workspace/source-space/bid-event-frontend/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~
```

**Comment by LuisYagof** [comment]
Same problem. I've tried upgrading vue-i18n from version 9.1.0 to 9.3.0 and I'm still getting the same error:

`  VITE v4.3.9  ready in 1025 ms

  ➜  Local:   http://127.0.0.1:3001/
  ➜  Network: use --host to expose
  ➜  press h to show help
X [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)
    at tryNodeResolve (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at Object.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64148:21
    at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23689:34
    at async requestCallbacks.on-resolve (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1360:22)
    at async handleRequest (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:723:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23669:19)
    at handlePlugins (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1279:21)
    at buildOrContextImpl (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:968:5)
    at Object.buildOrContext (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:776:5)
    at D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:2172:27)
    at Object.context (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:2012:58)
    at prepareEsbuildOptimizerRun (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44450:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~

D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1360:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
    at failureErrorWithLog (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1636:15)
    at D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1048:25
    at D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1512:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in 
"@intlify/shared" package
          at packageEntryFailure (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
          at resolvePackageEntry (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)
          at tryNodeResolve (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
          at Context.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
          at Object.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64148:21
          at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23689:34
          at async requestCallbacks.on-resolve (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:1360:22)
          at async handleRequest (D:\Users\luisyago.fernandez\Projects\Repsol_Carga\CarrierCompanyFront\app\node_modules\esbuild\lib\main.js:723:13),
      id: '',
      location: {
        column: 21,
        file: 'node_modules/esbuild/lib/main.js',
        length: 0,
        line: 1360,
        lineText: '        let result = await callback({\n' +
          '    at packageEntryFailure (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)\n' +
          '    at resolvePackageEntry (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)\n' +
          '    at tryNodeResolve (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)\n' +
          '    at Context.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)\n' +
          '    at Object.resolveId (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64148:21\n' +
          '    at async file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23689:34\n' +
          '    at async requestCallbacks.on-resolve (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:1360:22)\n' +
          '    at async handleRequest (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:723:13)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1279,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23669:19)\n' +
              '    at handlePlugins (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:1279:21)\n' +
              '    at buildOrContextImpl (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:968:5)\n' +
              '    at Object.buildOrContext (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:776:5)\n' +
              '    at D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:2172:68\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.context (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:2172:27)\n' +
              '    at Object.context (D:\\Users\\luisyago.fernandez\\Projects\\Repsol_Carga\\CarrierCompanyFront\\app\\node_modules\\esbuild\\lib\\main.js:2012:58)\n' +
              '    at prepareEsbuildOptimizerRun (file:///D:/Users/luisyago.fernandez/Projects/Repsol_Carga/CarrierCompanyFront/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44450:35)',     
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 21,
            file: 'node_modules/vue-i18n/dist/vue-i18n.cjs',
            length: 17,
            line: 8,
            lineText: "var shared = require('@intlify/shared');",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'
    }
  ],
  warnings: []
}`

**Comment by ponychoker** [comment]
yep, version 9.3.0 does not work well

**Comment by ConradMeyer** [comment]
Same problem here...

**Comment by RASH-WJ** [comment]
So, is there a solution

**Comment by RASH-WJ** [comment]
So, is there a solution? It's really urgent

**Comment by wangbincumt** [comment]
same problem 

 node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~

text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'

**Comment by 1906556657** [comment]
所以到底怎么解决啊

**Comment by FTZANKE** [comment]
<img width="1706" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/85344218/5b12fa89-4ebc-4dce-9a1b-fbf6f2db09c6">
9.2.2 -> 9.3.0


扣绩效，百分之几？30？还是 50？

**Comment by kazupon** [comment]
Hmm 🤔 
In the case of this issue, it seems to be happening in the monorepo case.
Looks like vue-i18n in cjs is being loaded by vite.

**Comment by FTZANKE** [comment]
"vue-i18n": "^9.3.0", 
 
 node_modules/.pnpm/vue-i18n@9.3.0_vue@3.3.4/node_modules/@intlify/shared/package.json
 这个文件 exports 选项换成这个就能正常了
 
 ```
 "exports": {
    ".": {
      "import": {
        "node": "./index.mjs",
        "default": "./dist/shared.esm-bundler.js"
      },
      "require": "./index.js"
    },
    "./dist/*": "./dist/*",
    "./index.mjs": "./index.mjs",
    "./package.json": "./package.json"
  },
 ```

**Comment by FTZANKE** [comment]
> <img alt="图像" width="1098" src="https://user-images.githubusercontent.com/85344218/265872453-799fe892-151c-4270-8570-3e48b9f4881e.png"> 9.2.2 -> 9.3.0
> 扣绩效，百分之几？30？还是50？



> 

等于说把这个选项回滚到 9.2.2 的代码能正常跑，具体修复看官方

**Comment by kirklin** [comment]
I wanted to let you know that I have successfully resolved the issue by following your modification suggestion and setting up `vue-i18n.esm-bundler.js`. The project is now running smoothly. Thank you for your assistance! Additionally, I have considered your suggestion about the `unplugin-vue-i18n` plugin, and I think it's a great idea. I will definitely consider using it to optimize both development and production builds.
Once again, thank you for your advice and support!

**Comment by kirklin** [comment]
# 中文版：issue总结：
# 解决 Vite 配置中的 vue-i18n 问题

如果你在使用 Vite 构建项目时遇到了 Vue I18n 相关的问题，下面的解决方案可以帮助你解决这个问题。

## 修改 Vite 配置

在你的 Vite 配置文件中，有一个需要修改的部分，将它改为以下内容可以解决问题：

```javascript
// vite.config.js

// 在 resolve 部分添加别名(alias)
resolve: {
  alias: {
    "vue-i18n": "vue-i18n/dist/vue-i18n.cjs.js", // 修改前
    "vue-i18n": "vue-i18n/dist/vue-i18n.esm-bundler.js", // 修改后
  },
},
```
这个更改将告诉 Vite 使用 vue-i18n.esm-bundler.js 而不是 vue-i18n.cjs.js，从而解决问题。

# 使用 unplugin-vue-i18n 插件
此外，我们强烈建议你使用 [unplugin-vue-i18n](https://github.com/antfu/unplugin-vue-i18n) 插件，它可以优化国际化配置，适用于开发和生产环境。以下是使用该插件的步骤：

# English version：

# Resolving Vue I18n Issues in Vite Configuration

If you are encountering Vue I18n-related issues while building your project with Vite, the following solutions can help you address the problem.

## Modify Your Vite Configuration

In your Vite configuration file, there's a section that needs to be adjusted. Changing it to the following content can resolve the issue:

```javascript
// vite.config.js

// Add an alias in the resolve section
resolve: {
  alias: {
    "vue-i18n": "vue-i18n/dist/vue-i18n.cjs.js", // Before modification
    "vue-i18n": "vue-i18n/dist/vue-i18n.esm-bundler.js", // After modification
  },
},
```

This change will instruct Vite to use vue-i18n.esm-bundler.js instead of vue-i18n.cjs.js, thereby resolving your issue.

# Use the unplugin-vue-i18n Plugin
Furthermore, we strongly recommend using the `unplugin-vue-i18n` plugin, which optimizes internationalization configuration for both development and production environments.

**Comment by RASH-WJ** [comment]
Thank you.

**Comment by rubjo** [comment]
Thank you for solving this so quickly!

I tried setting up `unplugin-vue-i18n`, although I must confess I think it's hard to understand what exactly the benefits are. My Vite/PrimeVue setup started to throw a lot of errors when I tried following the steps. Would love to see an example of how to use it with dynamically loaded locales, if the benefits of using it are tangible.
