### ISSUE TITLE
Vercel nuxt deploy caught error

### ISSUE THREAD

**Issue by icai** [intlify/vue-i18n-next#1539]
### Reporting a bug?

type: Serverless Function

```
roperties of undefined (reading 't')
    at formatParts (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)
    at msg (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)
    at evaluateMessage (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)
    at translate (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)
    at file:///var/task/chunks/app/server.mjs:2124:46
    at wrapWithDeps (file:///var/task/chunks/app/server.mjs:2108:13)
    at Proxy.t (file:///var/task/chunks/app/server.mjs:2124:12)
    at file:///var/task/chunks/app/_nuxt/AuthLayout-c3feaaac.mjs:563:66
    at Object.renderFnWithContext [as default] (/var/task/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:357:13)
    at Proxy.<anonymous> (file:///var/task/node_modules/vue-router/dist/vue-router.mjs:2270:60)
vue:error TypeError: Cannot read properties of undefined (reading 't')
    at formatParts (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)
    at msg (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)
    at evaluateMessage (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)
    at translate (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)
    at file:///var/task/chunks/app/server.mjs:2124:46
    at wrapWithDeps (file:///var/task/chunks/app/server.mjs:2108:13)
    at Proxy.t (file:///var/task/chunks/app/server.mjs:2124:12)
    at file:///var/task/chunks/app/_nuxt/AuthLayout-c3feaaac.mjs:572:76
    at Object.renderFnWithContext [as default] (/var/task/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:357:13)
    at Proxy.<anonymous> (file:///var/task/node_modules/vue-router/dist/vue-router.mjs:2270:60)
vue:error TypeError: Cannot read properties of undefined (reading 't')
    at formatParts (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)
    at msg (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)
    at evaluateMessage (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)
    at translate (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)
    at file:///var/task/chunks/app/server.mjs:2124:46
    at wrapWithDeps (file:///var/task/chunks/app/server.mjs:2108:13)
    at Proxy.t (file:///var/task/chunks/app/server.mjs:2124:12)
    at file:///var/task/chunks/app/_nuxt/AuthLayout-c3feaaac.mjs:581:76
    at Object.renderFnWithContext [as default] (/var/task/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:357:13)
    at Proxy.<anonymous> (file:///var/task/node_modules/vue-router/dist/vue-router.mjs:2270:60)
vue:error TypeError: Cannot read properties of undefined (reading 't')
    at formatParts (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)
    at msg (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)
    at evaluateMessage (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)
    at translate (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)
    at file:///var/task/chunks/app/server.mjs:2124:46
    at wrapWithDeps (file:///var/task/chunks/app/server.mjs:2108:13)
    at Proxy.t (file:///var/task/chunks/app/server.mjs:2124:12)
    at file:///var/task/chunks/app/_nuxt/AuthLayout-c3feaaac.mjs:590:76
    at Object.renderFnWithContext [as default] (/var/task/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:357:13)
    at Proxy.<anonymous> (file:///var/task/node_modules/vue-router/dist/vue-router.mjs:2270:60)
```

### Expected behavior

I tried to deploy the project  https://github.com/icai/nuxt-starter  to Vercel but caught some errors. I tried to locally build and run, is okay.

### Reproduction

<https://nuxt-starter-d8jt5b7fs-icai.vercel.app>

<img width="607" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/1061012/4a7d090f-8a6a-4a24-b9a4-3d55a99cfcc9">

### System Info

```shell
<img width="607" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/1061012/4a7d090f-8a6a-4a24-b9a4-3d55a99cfcc9">

local system info:

```
  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 208.39 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.4
  npmPackages:
    vue-i18n: ^9.3.0 => 9.3.0 
```



### Screenshot

<img width="466" alt="image" src="https://github.com/intlify/vue-i18n-next/assets/1061012/7ad48df0-25d5-43fa-948e-2e2f10ac5776">


### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by icai** [comment]
I try to use `@nuxtjs/i18n-edge`, is okay.
