### ISSUE TITLE
No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

### ISSUE THREAD

**Issue by TryChai** [intlify/vue-i18n-next#1709]
### Reporting a bug?

element plus 从2.3.1 升级到 2.5.3 ，vue-il8n 从9.2.2 升级到 9.9.0 报错
No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package

### Expected behavior

不报错 正常运行

### Reproduction

Error: No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package
    at e (file:///G:/project/lky-ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:25)
    at n (file:///G:/project/lky-ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:646)

### System Info

```shell
chorme
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by ntnyq** [comment]
https://github.com/element-plus/element-plus/issues/13609

**Comment by kazupon** [comment]
please more reproduction context infomation. 🙏

**Comment by kazupon** [comment]
This is not a vue-i18n issue. The error `No known conditions for "./lib/locale/lang/zh-cn" specifier in "element-plus" package` is caused by Element Plus's `package.json` `exports` field not properly defining the export condition for that path.

As @ntnyq pointed out, this is tracked on the Element Plus side: [element-plus#13609](https://github.com/element-plus/element-plus/issues/13609).

Closing this as it's an Element Plus issue, not a vue-i18n bug.

Thanks!
