### ISSUE TITLE
TypeError: o is not a function

### ISSUE THREAD

**Issue by moh1434** [intlify/vue-i18n-next#931]
### Reporting a bug?

I get `TypeError: o is not a function` only on production (even with version 9.2.0-beta.30).

package.json:
```
  "dependencies": {
    "vue": "^3.2.25",
    "vue-i18n": "9.2.0-beta.30",
    "vue-router": "4"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.3.0",
   ...
}
```
vite.config.ts:
  ```
  vueI18n({
      // you need to set i18n resource including paths !
      include: path.resolve(__dirname, './src/locales/**'),
    }),
```
But if i try version `"vue-i18n": "9.2.0-beta.13"`, I get:
```
TypeError: l is not a function
    at Js (core-base.esm-browser.prod.js:6:22376)
    at Qs (core-base.esm-browser.prod.js:6:21752)
    at vue-i18n.runtime.esm-bundler.js:489:48
    at V (vue-i18n.runtime.esm-bundler.js:446:19)
    at K (vue-i18n.runtime.esm-bundler.js:489:16)
    at setup (TheHeader.vue:8:11)
    at mt (runtime-core.esm-bundler.js:155:22)
    at zc (runtime-core.esm-bundler.js:7056:29)
    at Kc (runtime-core.esm-bundler.js:7012:11)
    at Ee (runtime-core.esm-bundler.js:4922:13)

```

### Expected behavior

No errors on production.

### Reproduction

In App.vue:
```
<script setup lang="ts">
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
</script>
<template>
  {{ t('test') }}
</template>
```
In vite.config.ts add:
  ```
  vueI18n({
      // you need to set i18n resource including paths !
      include: path.resolve(__dirname, './src/locales/**'),
    }),
```
And  run `yarn build`, then `yarn preview`

### System Info

```shell
System:
    OS: Linux 5.4 Linux Mint 20.3 (Una)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 624.43 MB / 7.57 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.3.0 => 3.3.0 
    @vitejs/plugin-vue: ^2.0.0 => 2.2.2 
    vite: ^2.7.2 => 2.8.4 
    vue: ^3.2.25 => 3.2.31 
    vue-i18n: 9.2.0-beta.30 => 9.2.0-beta.30 
    vue-router: 4 => 4.0.12 
    vue-tsc: ^0.29.8 => 0.29.8
```

### Screenshot

Screenshot of reproduction error(with version **9.2.0-beta.30**):
![asaaa](https://user-images.githubusercontent.com/61632563/154769811-2a476760-9b13-4a34-839c-f621a75578b5.png)

Screenshot of reproduction error(with version **9.2.0-beta.13**):
![v13](https://user-images.githubusercontent.com/61632563/154770186-b2951dc7-abc6-44a5-8799-191245b7283a.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by moh1434** [comment]
I solved this issue by replacing **en.ts**:
```
export default {
  test: 'Test en',
};
```
with **en.json**:
```
{
  "test": "Test en",
}
```
