### ISSUE TITLE
No matching export for import "CoreWarnCodes"

### ISSUE THREAD

**Issue by chindit** [intlify/vue-i18n-next#978]
### Reporting a bug?

On a simple project with only these dependencies:
`"devDependencies": {
    "nuxt3": "latest",
    "sass": "^1.49.10"
  },
  "dependencies": {
    "@intlify/nuxt3": "^0.1.10",
    "@intlify/core-base": "^9.2.0-beta.34",
    "axios":"^0.26.1",
    "vue-i18n": "^9.2.0-beta.34"
  }`

I got the following error when running `nuxi build` (nuxi is the Nuxt CLI command, which use Vite):
```
ERROR  20:31:05 [vite] error while updating dependencies:                                                                                                                                               20:31:05
Error: Build failed with 8 errors:
node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:9: ERROR: No matching export in "node_modules/@intlify/core-base/dist/core-base.esm-bundler.js" for import "CoreWarnCodes"
node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:44: ERROR: No matching export in "node_modules/@intlify/core-base/dist/core-base.esm-bundler.js" for import "CompileErrorCodes"
node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:63: ERROR: No matching export in "node_modules/@intlify/core-base/dist/core-base.esm-bundler.js" for import "DEFAULT_LOCALE"
node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:101: ERROR: No matching export in "node_modules/@intlify/core-base/dist/core-base.esm-bundler.js" for import "setFallbackContext"
node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:7:199: ERROR: No matching export in "node_modules/@intlify/core-base/dist/core-base.esm-bundler.js" for import "getFallbackContext"
...
    at failureErrorWithLog (/home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:1599:15)
    at /home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:1245:28
    at runOnEndCallbacks (/home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:1030:63)
    at buildResponseToResult (/home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:1243:7)
    at /home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:1352:14
    at /home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:662:9
    at handleIncomingPacket (/home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/home/david/Documents/Perso/Code/dadapictures-app/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
```

### Expected behavior

A clean build ^^

Please note that a dev build does not trigger the error

### Reproduction

Try a simple Nuxt3 project with i18n

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.29 GB / 15.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.5.0 - /usr/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Chromium: 100.0.4896.60
    Firefox: 98.0.2
  npmPackages:
    @intlify/core-base: ^9.2.0-beta.34 => 9.2.0-beta.34 
    @intlify/nuxt3: ^0.1.10 => 0.1.10 
    vue-i18n: ^9.2.0-beta.34 => 9.2.0-beta.34
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting.

This issue is happening in intlify/nuxt3. So it should be reported to that repository.
https://github.com/intlify/nuxt3

so, I’ll close this issue.

BTW, I am focusing on nuxt/i18n.
So intlify/nuxt3 might not be maintained

**Comment by misaon** [comment]
I have simmilar problem.

I have following error on Nuxt 3.1.1
```
node_modules/.pnpm/vue-i18n-routing@0.10.2_vue-i18n@9.3.0-beta.16/node_modules/vue-i18n-routing/dist/vue-i18n-routing.mjs:3:9: ERROR: No matching export in "node_modules/.pnpm/@intlify+vue-i18n-bridge@0.8.0_vue-i18n@9.3.0-beta.16/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs" for import "useI18n"
```
