### ISSUE TITLE
i18n with vite build, remote messages, doesn't work

### ISSUE THREAD

**Issue by hjess** [intlify/vue-i18n-next#988]
I have multiple (currently 2) translation files, specified in YAML. I want those files to be _outside_ of source control, so they can be changed and deployed without a new build from source. I'm using Vue3 (3.2.31) and vue-i18n (9.1.9), and vite (2.8.5). The files are preloaded using axios and yamlParse.

This works great in dev/hmr mode, but breaks in prod mode, when accessing `someVueInstance.$t` (I think); the message in the dev console is:
```
vendor.40da3268.js:4 TypeError: l is not a function
    at $0 (vendor.40da3268.js:41:3687)
    at Ym (vendor.40da3268.js:41:3057)
    at vendor.40da3268.js:45:2739
    at F (vendor.40da3268.js:45:2607)
    at Proxy.P (vendor.40da3268.js:45:2734)
    at Proxy.ae (index.87f71f0d.js:1:4611)
    at Lc (vendor.40da3268.js:4:3884)
    at op.me [as fn] (vendor.40da3268.js:4:24374)
    at op.run (vendor.40da3268.js:1:5090)
    at P (vendor.40da3268.js:4:24652)
```

The code looks like this:
```
// main.ts
import { createApp } from 'vue';

import App from '@/App.vue';
import {Net,Urls} from '@/utils/Net';
import {i18nSetup, i18nInstall} from '@/plugins/i18n';
import router from '@/router';
import axios from 'axios';

const app = createApp(App);

app.config.globalProperties.axios = axios;

// fetch list of supported languages
Net.get(Urls.localeConfig())
    .then((data) => {
        // fetch all langage message/translation files
        i18nSetup(data.data)
            .then(() => {
                app.use(i18nInstall());
                app.use(router);
                app.mount('#app');
            });
    });
```

```
// i18n.ts
import type { App } from 'vue';
import { createI18n } from 'vue-i18n';
import { parse as yamlParse } from 'yaml';
import { Net, Urls } from '@/utils/Net';

const localeData: any = {
            config: undefined,
            lang: {},
            locale: '',
        };

const i18nSetup = (localeConfig: any) => {
    // fetch all messages files
    localeData.config = localeConfig;
    const setup = Promise.all(Object.keys(localeData.config).map((lang) => {
        const result = Net.get(Urls.locale(lang));

        // yaml parse to convert to a JS object
        result.then((data) => localeData.lang[lang] = yamlParse(data.data));
        return result;
    }));

    setup.catch((err) => console.error('i18nSetup: cannot get locales; error:',err))
    return setup;
}

const i18nInstall = () => {
    const i18n = createI18n({
        fallbackLocale: 'en-US',
        globalInjection: true,
        globalInstall: true,
        legacy: false,
        locale: 'en-US',
        messages: localeData.lang,
    });
    return i18n;
};

export {i18nSetup, localeData, i18nInstall};
```

Can anyone post a working example? I'm not sure where/who to blame, as this works properly in development (HMR) mode, and there are no obvious issues in loading the messages via axios, prior to instantiating vue-i18n, in prod mode.

Help???

_Originally posted by @hjess in https://github.com/intlify/vue-i18n-next/discussions/985_

**Comment by kazupon** [comment]
I've just commented in there
https://github.com/intlify/vue-i18n-next/discussions/985#discussioncomment-2589283
